#!/bin/bash

set -e

ex=echo

echo "$0: Started at $(date)";

restore_volume() {
cat <<EOF | ./jsql
UPDATE volumes SET available = 1 WHERE name = '$1';
EOF
}

close_exam_volume() {
exam_volume=`cat $1 || echo ''`
cat <<EOF | ./jsql
UPDATE volumes SET available = 0 WHERE name = '$exam_volume';
EOF
}

restore_turned_off_volumes() {
	if [ -f $1 ]; then
		for x in `cat $1`; do
			restore_volume $x
		done
	fi
	rm -f $1
}

echo "> Restoring turned off volumes..."
restore_turned_off_volumes .turned_off_volumes
echo "> Closing exam volume..."
close_exam_volume .exam_volume
echo "> Done"

# sed -i 's/\(\$ContestEnv\s*=\s*\)[0-9]\+/\10/' $HOME/public_html/config.php
