#!/bin/bash

set -e

usage() {
	echo "Usage: $0 <volume>"
}

if [ -z $1 ]; then
	usage
	exit 0
fi

volume=$1

remember_available_volumes() {
cat <<EOF | ./jsql | tail -n +2 > $1
SELECT name FROM volumes WHERE available=1;
EOF
}

enable_only() {
cat <<EOF | ./jsql
UPDATE volumes SET available = 0;
UPDATE volumes SET available = 1 WHERE name = '$1';
UPDATE problems SET available = 1 WHERE volume = '$1';
EOF
}

rm -f .turned_off_volumes
remember_available_volumes .turned_off_volumes

echo "> Enabling only $volume"
enable_only $volume

rm -f .exam_volume
echo $volume > .exam_volume

echo "> Exam started at $(date)"
